<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_t-shirts</name>
   <tag></tag>
   <elementGuidId>7ceff42f-6ac2-43f6-ac8a-e37e2ba8a504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-color-state.a-text-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/span[2]/div/h1/div/div/div/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d4d4436-b370-470b-a150-bb5cedc9d4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-state a-text-bold</value>
      <webElementGuid>7e5d4011-cb42-4534-a8b2-a524791c616c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;t-shirts&quot;</value>
      <webElementGuid>93fd8990-a8ff-4610-b841-3ed5dd5d8076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/span[@class=&quot;rush-component&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=UPPER template=RESULT_INFO_BAR widgetId=result-info-bar&quot;]/h1[@class=&quot;a-size-base s-desktop-toolbar a-text-normal&quot;]/div[@class=&quot;s-desktop-width-max sg-row-align-items-center s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-14-of-20 sg-col-18-of-24 sg-col s-breadcrumb sg-col-10-of-16 sg-col-6-of-12&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;a-section a-spacing-small a-spacing-top-small&quot;]/span[@class=&quot;a-color-state a-text-bold&quot;]</value>
      <webElementGuid>ef028f9e-2c63-475a-8efc-aded034a2020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/span[2]/div/h1/div/div/div/div/span[3]</value>
      <webElementGuid>c6f3d91b-e0a6-4a7c-a4cd-6671e0e9df48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[3]</value>
      <webElementGuid>5c03791e-8079-4fd4-916f-1c03a22609f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&quot;t-shirts&quot;' or . = '&quot;t-shirts&quot;')]</value>
      <webElementGuid>f3e32843-05d9-421e-8799-172e02fa9893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
