<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>b9627609-9348-4401-b40a-4e7ec0a6aef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-price-whole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/span/div/div/div[3]/div[3]/div/div/a/span/span[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c3250e3-d86f-4027-a64a-7d21297d23fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-price-whole</value>
      <webElementGuid>b31d14f4-ba6b-4bde-bb8b-8343f0336216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19.</value>
      <webElementGuid>d8909f95-d16f-4c04-b3f4-71d704977868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 sg-col s-widget-spacing-small sg-col-4-of-20&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-v2rh3j15wdcp4q29xeaptoa72x6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section a-spacing-base&quot;]/div[@class=&quot;a-section a-spacing-small puis-padding-left-small puis-padding-right-small&quot;]/div[@class=&quot;a-section a-spacing-none a-spacing-top-small s-price-instructions-style&quot;]/div[@class=&quot;a-row a-size-base a-color-base&quot;]/div[@class=&quot;a-row&quot;]/a[@class=&quot;a-link-normal s-no-hover s-underline-text s-underline-link-text s-link-style a-text-normal&quot;]/span[@class=&quot;a-price&quot;]/span[2]/span[@class=&quot;a-price-whole&quot;]</value>
      <webElementGuid>15e8c173-aa86-4597-bed2-4e2dad0c262e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/span/div/div/div[3]/div[3]/div/div/a/span/span[2]/span[2]</value>
      <webElementGuid>dd3dfc00-6eaf-4bcb-8a90-d71cb3ee5d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span/span[2]/span[2]</value>
      <webElementGuid>c0757c13-b3ad-4d19-9d6c-9f9349af088e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '19.' or . = '19.')]</value>
      <webElementGuid>e16b3ba9-5eef-4571-940c-c8e7c8e8772c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
